# Generated by Django 5.1.3 on 2024-12-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_service', '0004_remove_collection_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='recipes',
        ),
        migrations.AlterField(
            model_name='collection',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='collection',
            name='recipes',
            field=models.JSONField(default=''),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
