# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import collection_service.src.grpc.stubs.recipe_pb2 as recipe__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recipe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecipeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecipes = channel.unary_unary(
                '/de.benedikt_schwering.thicnd.stubs.RecipeService/GetRecipes',
                request_serializer=recipe__pb2.Null.SerializeToString,
                response_deserializer=recipe__pb2.RecipesResponse.FromString,
                _registered_method=True)
        self.GetRecipe = channel.unary_unary(
                '/de.benedikt_schwering.thicnd.stubs.RecipeService/GetRecipe',
                request_serializer=recipe__pb2.RecipeIdRequest.SerializeToString,
                response_deserializer=recipe__pb2.RecipeResponse.FromString,
                _registered_method=True)
        self.GetTotalIngredients = channel.unary_unary(
                '/de.benedikt_schwering.thicnd.stubs.RecipeService/GetTotalIngredients',
                request_serializer=recipe__pb2.RecipeIdRequest.SerializeToString,
                response_deserializer=recipe__pb2.TotalIngredientsResponse.FromString,
                _registered_method=True)
        self.GetAssociatedTags = channel.unary_unary(
                '/de.benedikt_schwering.thicnd.stubs.RecipeService/GetAssociatedTags',
                request_serializer=recipe__pb2.RecipeIdRequest.SerializeToString,
                response_deserializer=recipe__pb2.AssociatedTagsResponse.FromString,
                _registered_method=True)
        self.CreateRecipe = channel.unary_unary(
                '/de.benedikt_schwering.thicnd.stubs.RecipeService/CreateRecipe',
                request_serializer=recipe__pb2.CreateRecipeRequest.SerializeToString,
                response_deserializer=recipe__pb2.RecipeResponse.FromString,
                _registered_method=True)
        self.UpdateRecipe = channel.unary_unary(
                '/de.benedikt_schwering.thicnd.stubs.RecipeService/UpdateRecipe',
                request_serializer=recipe__pb2.UpdateRecipeRequest.SerializeToString,
                response_deserializer=recipe__pb2.RecipeResponse.FromString,
                _registered_method=True)
        self.DeleteRecipe = channel.unary_unary(
                '/de.benedikt_schwering.thicnd.stubs.RecipeService/DeleteRecipe',
                request_serializer=recipe__pb2.RecipeIdRequest.SerializeToString,
                response_deserializer=recipe__pb2.Null.FromString,
                _registered_method=True)


class RecipeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRecipes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalIngredients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssociatedTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecipeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecipes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecipes,
                    request_deserializer=recipe__pb2.Null.FromString,
                    response_serializer=recipe__pb2.RecipesResponse.SerializeToString,
            ),
            'GetRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecipe,
                    request_deserializer=recipe__pb2.RecipeIdRequest.FromString,
                    response_serializer=recipe__pb2.RecipeResponse.SerializeToString,
            ),
            'GetTotalIngredients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalIngredients,
                    request_deserializer=recipe__pb2.RecipeIdRequest.FromString,
                    response_serializer=recipe__pb2.TotalIngredientsResponse.SerializeToString,
            ),
            'GetAssociatedTags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssociatedTags,
                    request_deserializer=recipe__pb2.RecipeIdRequest.FromString,
                    response_serializer=recipe__pb2.AssociatedTagsResponse.SerializeToString,
            ),
            'CreateRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecipe,
                    request_deserializer=recipe__pb2.CreateRecipeRequest.FromString,
                    response_serializer=recipe__pb2.RecipeResponse.SerializeToString,
            ),
            'UpdateRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecipe,
                    request_deserializer=recipe__pb2.UpdateRecipeRequest.FromString,
                    response_serializer=recipe__pb2.RecipeResponse.SerializeToString,
            ),
            'DeleteRecipe': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecipe,
                    request_deserializer=recipe__pb2.RecipeIdRequest.FromString,
                    response_serializer=recipe__pb2.Null.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'de.benedikt_schwering.thicnd.stubs.RecipeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('de.benedikt_schwering.thicnd.stubs.RecipeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecipeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRecipes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/de.benedikt_schwering.thicnd.stubs.RecipeService/GetRecipes',
            recipe__pb2.Null.SerializeToString,
            recipe__pb2.RecipesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/de.benedikt_schwering.thicnd.stubs.RecipeService/GetRecipe',
            recipe__pb2.RecipeIdRequest.SerializeToString,
            recipe__pb2.RecipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTotalIngredients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/de.benedikt_schwering.thicnd.stubs.RecipeService/GetTotalIngredients',
            recipe__pb2.RecipeIdRequest.SerializeToString,
            recipe__pb2.TotalIngredientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssociatedTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/de.benedikt_schwering.thicnd.stubs.RecipeService/GetAssociatedTags',
            recipe__pb2.RecipeIdRequest.SerializeToString,
            recipe__pb2.AssociatedTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/de.benedikt_schwering.thicnd.stubs.RecipeService/CreateRecipe',
            recipe__pb2.CreateRecipeRequest.SerializeToString,
            recipe__pb2.RecipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/de.benedikt_schwering.thicnd.stubs.RecipeService/UpdateRecipe',
            recipe__pb2.UpdateRecipeRequest.SerializeToString,
            recipe__pb2.RecipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRecipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/de.benedikt_schwering.thicnd.stubs.RecipeService/DeleteRecipe',
            recipe__pb2.RecipeIdRequest.SerializeToString,
            recipe__pb2.Null.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
