name: Python Tests

on:
  pull_request:
    branches:
      - 'next'
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings.test
          SECRET_KEY_DJANGO: ${{ secrets.SECRET_KEY_DJANGO }}
        run: |
          python manage.py test
